package com.dingtao.common.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dingtao.common.bean.login.LoginBean;
import com.dingtao.common.bean.homepage.LsjlBean;

import com.dingtao.common.dao.LoginBeanDao;
import com.dingtao.common.dao.LsjlBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loginBeanDaoConfig;
    private final DaoConfig lsjlBeanDaoConfig;

    private final LoginBeanDao loginBeanDao;
    private final LsjlBeanDao lsjlBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loginBeanDaoConfig = daoConfigMap.get(LoginBeanDao.class).clone();
        loginBeanDaoConfig.initIdentityScope(type);

        lsjlBeanDaoConfig = daoConfigMap.get(LsjlBeanDao.class).clone();
        lsjlBeanDaoConfig.initIdentityScope(type);

        loginBeanDao = new LoginBeanDao(loginBeanDaoConfig, this);
        lsjlBeanDao = new LsjlBeanDao(lsjlBeanDaoConfig, this);

        registerDao(LoginBean.class, loginBeanDao);
        registerDao(LsjlBean.class, lsjlBeanDao);
    }
    
    public void clear() {
        loginBeanDaoConfig.clearIdentityScope();
        lsjlBeanDaoConfig.clearIdentityScope();
    }

    public LoginBeanDao getLoginBeanDao() {
        return loginBeanDao;
    }

    public LsjlBeanDao getLsjlBeanDao() {
        return lsjlBeanDao;
    }

}
